name: Build Java Maven Project

on:
  push:
    branches:
      - main  # executa sempre que há push para a branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4


      # Configura o Java (versão 24)
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   
          java-version: '24'


      # Executa o Maven build
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Copia o jar para a raiz do repositório
      - name: Copy JAR to root
        run: cp target/*.jar .

      # Publica o artefacto do build (ficheiro .jar)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: todoapp-jar
          path: target/*.jar
