name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - reminder_artur
      - mail_mafas
      - QR_joana
      - Jun's-Branch-PDF
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do código com histórico completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # IMPORTANTE: necessário para Sonar ver histórico e branches

      # Instala o Java (ajusta a versão se o teu projeto usar outra)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Cache para SonarCloud (acelera builds)
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Compila o projeto e executa a análise no SonarCloud
      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # necessário para PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # token criado no SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.projectKey=LEI-122714_ToDoApp \
             -Dsonar.organization=lei-122714
